version: '3.9'
services:
  # Applications
  firestore-consumer:
    container_name: firestore-consumer
    build: ./nu.example.FirestoreConsumer/.
    image: firestoreconsumer:firestoreconsumer
    environment:
      FIRESTORE_EMULATOR_HOST: 'firebase-emulator:8080'
    networks:
      - 'kafka-example-network'
    depends_on:
      broker:
        condition: service_healthy
      kafka-schema-registry:
        condition: service_healthy

  firestore-producer:
    container_name: firestore-producer
    build: ./nu.example.FirestoreProducer/.
    image: firestoreproducer:firestoreproducer
    environment:
      FIRESTORE_EMULATOR_HOST: 'firebase-emulator:8080'
    networks:
      - 'kafka-example-network'
    depends_on:
      broker:
        condition: service_healthy
      kafka-schema-registry:
        condition: service_healthy

  duplicate-message-filter:
    container_name: duplicate-message-filter
    build: ./nu.example.DuplicateMessageFilter/.
    image: messagefilter:messagefilter
    networks:
      - 'kafka-example-network'
    depends_on:
      broker:
        condition: service_healthy
      cache:
        condition: service_healthy
      kafka-schema-registry:
        condition: service_healthy

  http-producer:
    container_name: http-producer
    build: ./nu.example.HttpProducer/.
    image: httpproducer:httpproducer
    networks:
      - 'kafka-example-network'
    ports:
      - '2100:80'
    depends_on:
      broker:
        condition: service_healthy
      kafka-schema-registry:
        condition: service_healthy

  # Kafka infra
  zookeeper:
    container_name: kafka-zookeeper
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SESSION_TIMEOUT_MS: 500000
      JVMFLAGS: '-Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf'
    volumes:
      - ./Kafka/Zookeeper/kafka_zookeeper_jaas.conf:/etc/zookeeper/zookeeper_jaas.conf
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 2s
      timeout: 10s
      retries: 20
    networks:
      - 'kafka-example-network'

  broker:
    container_name: kafka-broker
    image: wurstmeister/kafka:latest
    hostname: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf'
    volumes:
      - ./Kafka/Broker/kafka_server_jaas.conf:/etc/kafka/kafka_jaas.conf
    healthcheck:
      test: ['CMD', 'nc', '-vz', 'localhost', '9092']
      interval: 2s
      timeout: 10s
      retries: 20
    networks:
      - 'kafka-example-network'

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      broker:
        condition: service_healthy
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf'
    networks:
      - 'kafka-example-network'
    volumes:
      - ./Kafka/Broker/kafka_server_jaas.conf:/etc/kafka/kafka_jaas.conf
      - ./Kafka/Broker/config.properties:/etc/kafka/config.properties
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:9092 --create --if-not-exists --topic users --replication-factor 1 --partitions 1 --command-config /etc/kafka/config.properties
      kafka-topics --bootstrap-server broker:9092 --create --if-not-exists --topic users-filtered --replication-factor 1 --partitions 1 --command-config /etc/kafka/config.properties
      kafka-topics --bootstrap-server broker:9092 --create --if-not-exists --topic bank-accounts --replication-factor 1 --partitions 1 --command-config /etc/kafka/config.properties
      "

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SASL_PLAINTEXT://broker:9092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG:
        "org.apache.kafka.common.security.plain.PlainLoginModule required \
        username=\"admin\" \
        password=\"admin-secret\";"
    networks:
      - 'kafka-example-network'
    depends_on:
      broker:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '--output',
          '/dev/null',
          '--silent',
          '--head',
          '--fail',
          'http://kafka-schema-registry:8081/subjects',
        ]
      interval: 2s
      timeout: 10s
      retries: 20

  # Misc infra
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:9092"
                security.protocol: SASL_PLAINTEXT 
                sasl.mechanism: PLAIN
                sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
              schema-registry:
                url: "http://kafka-schema-registry:8081"

    ports:
      - 2000:8080
    networks:
      - 'kafka-example-network'
    depends_on:
      broker:
        condition: service_healthy
      kafka-schema-registry:
        condition: service_healthy

  firebase-emulator:
    container_name: firebase-emulator
    build: ./FirebaseEmulator
    hostname: firebase-emulator
    image: firebase-emulator:firebase-emulator
    volumes:
      - ./FirebaseEmulator:/app
      - ./FirebaseEmulator/Data:/data
    ports:
      # Firestore emulator port
      - 8080:8080
      # Firebase emulator UI port
      - 2001:5000
    networks:
      - 'kafka-example-network'

  cache:
    image: redis:latest
    hostname: cache
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass SUPER_SECRET_PASS
    volumes:
      - ./Cache/Data:/data
    networks:
      - 'kafka-example-network'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 1s
      timeout: 3s
      retries: 10

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '2002:8001'
    volumes:
      - ./Cache/RedisInsight:/db
    networks:
      - 'kafka-example-network'

networks:
  kafka-example-network:
    name: 'kafka-example-network'
