image:
  repository: examples/firestore-producer
  pullPolicy: Never
  tag: latest

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
